// Generated by CoffeeScript 1.6.2
var Box;

Box = (function() {
  function Box(value, x, y) {
    this.model = new Label(value);
    this.model.x = x;
    this.model.y = y;
  }

  return Box;

})();
