// Generated by CoffeeScript 1.6.2
var Mainloop, OBJECT_MARGIN, SCREEN_HEIGHT, SCREEN_WIDTH;

SCREEN_WIDTH = 800;

SCREEN_HEIGHT = 480;

OBJECT_MARGIN = 50;

Mainloop = (function() {
  function Mainloop() {
    this.game = new Game(SCREEN_WIDTH, SCREEN_HEIGHT);
    this.game.start();
  }

  Mainloop.prototype.run = function(result) {
    var box;

    box = new Box(result, Math.random() * (SCREEN_WIDTH - OBJECT_MARGIN) + OBJECT_MARGIN, Math.random() * (SCREEN_HEIGHT - OBJECT_MARGIN) + OBJECT_MARGIN);
    return this.game.rootScene.addChild(box.model);
  };

  return Mainloop;

})();
